remote_theme: chromatical/jekyll-materialdocs
plugins:
  - jekyll-remote-theme
logo: logo/bytes.png # an absolute or relative image path to use as the site logo
mdl_colors: indigo-pink # a supported Material Design Lite color scheme
copyright: bytes at work AG # will override the copyright notice (default is site title)
search: true # enabled by default, set to false to disable site search
menu_style: dropdown # will only show child menu items for the main item selected
